In [5]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[5]

5

In [7]:
arr[0:4]

array([0, 1, 2, 3])

In [8]:
arr[1:5]

array([1, 2, 3, 4])

In [2]:
arr = np.arange(1,11)

NameError: name 'np' is not defined

In [10]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
# #numpy is different because of its ability to broadcast

In [1]:
arr

NameError: name 'arr' is not defined

In [3]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
sliceofarr = arr[3:6]

In [5]:
sliceofarr

array([3, 4, 5])

In [6]:
sliceofarr = 99
sliceofarr

99

In [7]:
sliceofarr

99

In [8]:
sliceofarr = arr[3:6]

In [9]:
sliceofarr

array([3, 4, 5])

In [10]:
sliceofarr[:] = 99
sliceofarr

array([99, 99, 99])

In [11]:
arr

array([ 0,  1,  2, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
# it not only changed the particular variable but also to the original vector 

In [13]:
# data is not copied it broadcasted
arr_copy = arr.copy()

In [14]:
arr_copy


array([ 0,  1,  2, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy[:] = 100

In [16]:
arr

array([ 0,  1,  2, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [18]:
# copy method is specially made so that we can retrevie the original vector


Numpy Indexing and selecting


In [19]:
mymat = np.arange(1,10)

In [20]:
mymat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
mymat.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
mymat[2][1]

IndexError: invalid index to scalar variable.

In [23]:
mymat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
mymat = mymat.reshape(3,3)

In [25]:
mymat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
mymat[2][1]

8

In [27]:
mymat[2,1]

8

In [28]:
# Single bracket is more convenient
mymat[:2,1:]  # Take everything from 0th row till 1st row (dont include 2nd row) AnD from column 1 till end 

array([[2, 3],
       [5, 6]])

In [29]:
# think Indiviual rows and columne in clising a 2D 


In [30]:
mymat[:2] # Take everything till 2nd Row, Take All Columne since it is not specified 

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
arr = np.arange(1,11)

In [34]:
arr > 2

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True])

In [35]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])